name: Formatting

on:
  push:
    branches:
      - 'master'
      - 'staging**'
  pull_request:
    branches:
      '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # formatting and basic install on cpu-only machine
  formatting:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: environment
        run: |
          which python
          python --version
          pip install --upgrade pip
          pip --version

      - name: Install deepspeed
        run: |
          pip install .[dev,autotuning] git+https://github.com/microsoft/deepspeed-mii.git@injection-policies
          ds_report

      - name: Formatting checks
        run: |
           pre-commit run --all-files
